steps:
  #Maven build step to clean and install the project
  - name: 'maven'
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
    #Docker build step to containerize the application
  - name:  'gcr.io/cloud-builders/gcloud'
  script: |
    gcloud run deploy cloudrunservice --image us-east5-docker.pkg.dev/$PROJECT_ID/docker-repo/sandbox-0.0.1:$COMMIT_SHA \
      --region us-east5 --platform managed --allow-unauthenticated