steps:
  #Maven build step to clean and install the project
  - name: 'maven'
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
    #Docker build step to containerize the application
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      docker build -t $LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:$COMMIT_SHA .

images: [$LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:$COMMIT_SHA]

#logging options for the build process
options:
  logging: CLOUD_LOGGING_ONLY